#!/bin/sh

# An init script for Hubot on Debian-based systems with logging.  This assumes you have:
# 1) A user called `hubot` in charge of the bot.
# 2) A file called /opt/hubot/env that contains the Hubot credentials.
# 3) A directory /var/log/hubot which hubot has write permissions to
#
# To set the adapter either edit bin/hubot to specify what you want or adjust ARGS.
#
### BEGIN INIT INFO
# Provides:          hubot
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the hubot service
# Description:       starts the Hubot
### END INIT INFO

NAME="Hubot"
HUBOT_HOME="/opt/hubot"
LOGFILE="/var/log/hubot/hubot.log"
PIDFILE="/var/run/hubot.pid"
DAEMON="$HUBOT_HOME/bin/hubot"
ARGS="-a slack -n hubot"
ENV="$HUBOT_HOME/env"

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $NAME: "
    . $ENV
    start-stop-daemon --start --quiet --chuid hubot --make-pidfile --pidfile $PIDFILE --background --chdir $HUBOT_HOME --startas /bin/bash -- -c "exec ${DAEMON} ${ARGS} >> ${LOGFILE} 2>&1"
    log_end_msg 0
    ;;
  stop)
    log_daemon_msg "Stopping $NAME: "
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    log_end_msg 0
    ;;

  restart)
    log_daemon_msg "Stopping $NAME: "
	  start-stop-daemon --stop --quiet --pidfile $PIDFILE
	  log_end_msg 0
	  log_daemon_msg "Starting $NAME: "
	  . $ENV
    start-stop-daemon --start --quiet --chuid hubot --make-pidfile --pidfile $PIDFILE --background --chdir $HUBOT_HOME --startas /bin/bash -- -c "exec ${DAEMON} ${ARGS} >> ${LOGFILE} 2>&1"
	  log_end_msg 0
	  ;;

  status)
    PID=''
    if [ -f $PIDFILE ]
    then
        PID=$(cat $PIDFILE)
    fi

    if [ -n "$PID" ]
    then
	      echo "$NAME is running (pid $PID)."
        exit 0
    else
        echo "$NAME is not running."
        exit 1
    fi
    ;;

  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
