#!/bin/sh
################################################################################
## Name:  		check-df.sh
## Author:		FOXX (frozenfoxx@github.com)
## Date:		12/10/2008
## Description:		Modifies Solaris network adapter settings.
################################################################################
#
PATH=/sbin:/usr/bin/:/usr/sbin

echo "Configuring Network Interfaces"

case "$1" in

'start')
        ndd -set /dev/ce adv_1000fdx_cap 0
        ndd -set /dev/ce adv_1000hdx_cap 0
        ndd -set /dev/ce adv_100fdx_cap 1
        ndd -set /dev/ce adv_100hdx_cap 0
        ndd -set /dev/ce adv_10fdx_cap 0
        ndd -set /dev/ce adv_10hdx_cap 0
        ndd -set /dev/ce adv_autoneg_cap 0
        ;;
esac
exit 0
