#!/bin/sh

################################################################################
## Name:  		startVncServer
## Author:		FOXX (frozenfoxx@github.com)
## Date:		03/24/2008
## Description:		This is a DEVELOPMENT script, it is not currently 100%
##			functional.  It runs manually but not automatically.
################################################################################

umask 022
TERM=vt100
export TERM
XVNC=/usr/local/bin/vncserver

case "$1" in

'start')
  ## Start a new Xvnc server on :1
  $XVNC :1

  ## Allow hosts to connect to the newly-running Xvnc server
  DISPLAY=localhost:1
  export DISPLAY
  xhost +
  ;;

'stop')
  ## Attempt to kill any running Xvnc server on :1
  $XVNC -kill :1
  ;;

'restart')
  ## Attempt to kill any running Xvnc server on :1
  $XVNC -kill :1

  ## Start a new Xvnc server on :1
  $XVNC :1

  ## Allow hosts to connect to the newly-running Xvnc server
  DISPLAY=localhost:1
  export DISPLAY
  xhost +
  ;;
esac
exit 0
